### PR TITLE
Highlight current nav

### PR DESCRIPTION
**Pull request by r4j4h**

### CODE REVIEW

**Comment by GianlucaGuarini** [comment]
@r4j4h thanks it's a nice idea but why haven't you used directly the riot expressions like this?

``` html
<a href="blabla" class={ selected: this.selectedId === 'blabla' } />Blabla</a>
```

**Comment by r4j4h** [comment]
I don't know how in a riot expression to reference the element the expression is on.

The way that expression is written works, but I don't like the added redundancy of the href in the conditional because it's coupled. If the href changes, the conditional has to be changed.

Moreover, if the href changes dynamically, is the conditional expression still going to work? Maybe it shouldn't and those things don't really matter, but I think about them.

I think it can be done if it's made into a tag, but then that adds complexity unrelated to routing. Maybe that's a good thing, but I am happy with the amount of files in the example as is.

Can you help me get rid of that redundancy with the riot expression approach? I will go on and commit the changes, but here they are in a plunker http://plnkr.co/edit/Oz7osQBkxx1AHWiljmI0?p=preview :)

**Comment by GianlucaGuarini** [comment]
@r4j4h what about [this](http://plnkr.co/edit/LJs2kqRmcdt353Zi6DDQ?p=preview)?

**Comment by r4j4h** [comment]
I love it! Commit with that approach incoming

**Comment by GianlucaGuarini** [comment]
@r4j4h thank you for your contribution

**Pull request merged**
