### PR TITLE
Adds an example of if-else-elseif

### PR DESCRIPTION
**Pull request by cognitom**
This example was the answer to the issue https://github.com/riot/riot/issues/1931

``` html
<if cond={ hot }>
  <then><p>Hot beverage</p></then>
  <else><p>Cold beverage</p></else>
</if>
```

### CODE REVIEW

**Comment by GianlucaGuarini** [comment]
wow cool.. could you add the link to your demo also in the readme file please?

**Comment by cognitom** [comment]
@GianlucaGuarini thanks. I've added `Extra` section in README.
I think It's not `Basic` or `Advanced`. someone mentioned about "core tags" of Riot, but I'm not sure about that. Any thoughts?

**Comment by GianlucaGuarini** [comment]
Extra sounds good to me thanks again for this useful demo

**Comment by AndyDyer** [comment]
are there plans to move forward this or is it preferred to do if{foo} and if {!foo}

**Pull request merged**
