### PR TITLE
[WIP] Add Color Palette example

### PR DESCRIPTION
**Pull request by cognitom**
screen

I'd like to show how to create custom form element with Riot. The point is compatibility with native `<input>`, `<select>` and so on. It means:
- you can set or get the value via `value` attribute
- it fires `onchange` event just like `<input>` element

I think this example works fine, but needs some review. Some points could be controversial.
- `self.root.value`: feed back the value to its DOM
- `new Event('change')`: use the native event system to behave as a HTML element

Thoughts? Any feedback is welcome. I'm still guessing the best way is...

Try on plunker, thanks.
http://plnkr.co/edit/Csnx6EZmi4qNS5ZyKS5r?p=preview

### CODE REVIEW

**Comment by GianlucaGuarini** [comment]
@cognitom I have simplified your example ;) http://plnkr.co/edit/cT0QGvZ7Vxk8BohYnOeo?p=preview

**Comment by cognitom** [comment]
Aha, `this.root.onchange()` is a nice idea! Thanks.

**Comment by cognitom** [comment]
@GianlucaGuarini I'd like to pass the event object, too. Is there any good way to do that?
Think this case:
http://plnkr.co/edit/aZmYIBnoAsBUcv2Fdch9?p=preview

In this case `<color-palette>` and `<select>` is compatible and exchangeable. To do this, we need to mimic the behaviour of the native `<select>` with `event`.

``` html
<color-palette value={ color } onchange={ change } colors={ colors } />

and 

<select value={ color } onchange={ change }>
  <option each={ c in colors }>{ c }</option>
</select>
```

**Comment by GianlucaGuarini** [comment]
@cognitom ok you are right let's merge it

**Comment by cognitom** [comment]
Ok, I've found a bit sophisticated way to do this, and updated this PR ;-)

New:

``` js
click (e) {
  self.root.value = self.value = e.item.c
  self.triggerDomEvent('change')
}
self.on('sync', function() {
  self.value = opts.value
})
self.mixin('domEvent')
```

Before:

``` js

click (e) {
  self.root.value = self.value = e.item.c
  self.triggerDomEvent('change')
  flag = true
}
self.on('update', function() {
  if (!flag) self.value = opts.value
  flag = false
})
self.mixin('domEvent')
```

**Comment by GianlucaGuarini** [comment]
thanks @cognitom it looks fine to me now

**Pull request merged**
