### PR TITLE
Adds a minimal test

### PR DESCRIPTION
**Pull request by cognitom**
@GianlucaGuarini pls check this.

I've loaded the tags via `html2js`. It seems the best way at this point. Any suggestion or advice? Thanks.

cc: @dp-lewis

### CODE REVIEW

**Comment by cognitom** [comment]
Oh, someone has already made `karma-riot` preprocessor.
https://www.npmjs.com/package/karma-riot

**Comment by cognitom** [comment]
`karma-riot` seems not maintained long time. The supported Riot is v2.0.7.
How about ask the author to move the repo to `riot/karma-riot`?
https://github.com/teekz

**Comment by GianlucaGuarini** [comment]
@cognitom It looks good,  I would like to include `karma-riot` in our organization as well

**Comment by cognitom** [comment]
@GianlucaGuarini thanks for feedback. ok, I'll merge this.
I'm contacting @TeeKz via email, too.

**Comment by TeeKz** [comment]
Hey @cognitom, saw your tag here. I deleted my karma-riot repo and unpublished the npm package. I made it a while ago and was no longer maintaining it. Go ahead and use the repo name if you'd like :)

**Comment by cognitom** [comment]
@TeeKz thank you so much! :smile_cat: 
We'd like to use it. Could you give me an access to your repo on npm?
https://www.npmjs.com/~cognitom

**Comment by TeeKz** [comment]
I deleted(unpublished) it. Try making a new repo with your account with the
same name. Does it work?

On Fri, Sep 11, 2015 at 10:02 AM, Tsutomu Kawamura <notifications@github.com

**Comment by cognitom** [comment]
Oh, i c, thanks. I'll try it after making a new repo on GitHub.
I'd like to keep your name on `package.json`, can I?

**Comment by TeeKz** [comment]
Sure! Why not :)

On Fri, Sep 11, 2015 at 10:09 AM, Tsutomu Kawamura <notifications@github.com

**Comment by cognitom** [comment]
:smile:

**Comment by GianlucaGuarini** [comment]
@cognitom we could use this karma plugin in our unit test

**Comment by cognitom** [comment]
OK, done!
This is the new version.
https://github.com/riot/karma-riot

**Pull request merged**
