### PR TITLE
Using the iframes to render the content of the live editor

### PR DESCRIPTION
**Pull request by GianlucaGuarini**
This will fix all the issues due to the execution of the javascript code needed for the code editor in same sandbox where the riot rendering gets called

### CODE REVIEW

**Comment by GianlucaGuarini** [comment]
With these new features our editor should be really complete. Please test them first and let me know what you think @tipiirai @cognitom

**Comment by cognitom** [comment]
@GianlucaGuarini great!
Passing the data with hash looks hacky at first glance but works well. Nice idea!
I've confirmed that we can use multi byte letters, too.

I'd also like to add `each`, for example:

``` html
<sample>
  <h3>{ message }</h3>
  <ul>
    <li each={ techs }>{ name }</li>
  </ul>

  <script>
    this.message = 'Hello, Riot!'
    this.techs = [
      { name: 'HTML' },
      { name: 'JavaScript' },
      { name: 'CSS' }
    ]
  </script>

  <style scoped>
    :scope { font-size: 2rem }
    h3 { color: #444 }
    ul { color: #999 }
  </style>
</sample>
```

How about?

**Comment by GianlucaGuarini** [comment]
@cognitom it looks cool, maybe you can already update our example

**Comment by GianlucaGuarini** [comment]
why don't we have any link to our examples on our main site?

**Comment by cognitom** [comment]
@GianlucaGuarini now we're making it :v: 
https://github.com/riot/riot.github.io/pull/32

**Comment by cognitom** [comment]
I'm merging this PR once, then I'll update it, later.

**Comment by rsbondi** [comment]
Does not work in FF, tired windows and linux

**Comment by cognitom** [comment]
Oops, nice catch.
I've got `NS_ERROR_MALFORMED_URI` on FF.

**Comment by cognitom** [comment]
Quick check results on Mac and Win:
- Chrome: OK
- Safari: OK
- Firefox: NG
- Edge: OK
- IE11: OK
- IE10: OK
- IE9: OK

**Comment by cognitom** [comment]
OK, I've found the fix ;-)
I'll push it soon.

**Comment by cognitom** [comment]
Done.
@rsbondi could you check this URL?
http://riotjs.com/examples/live-editor/

**Comment by rsbondi** [comment]
Working now

**Comment by cognitom** [comment]
:v:

**Pull request merged**
