### PR TITLE
normalized examples script tags and other small fixes

### PR DESCRIPTION
**Pull request by GianlucaGuarini**
A few updates to make our examples more consistent across the whole repo

### CODE REVIEW

**Comment by cognitom** [comment]
Nice! Thank you.

**Comment by GianlucaGuarini** [comment]
I will try to fix the tests. But it seems that the path to the old router is broken http://riotjs.com/play/router/

**Comment by GianlucaGuarini** [comment]
the issue comes from `karma-riot` but I don't get it.. can you have a look at it please?

**Comment by cognitom** [comment]
Your change will fix it. I'd like to merge this now.
We might need some fix on karma-riot...

**Comment by cognitom** [comment]
@GianlucaGuarini yeah, I'll do it tomorrow. I got to go to bed... It's 3am Tokyo. See you :-)

**Comment by GianlucaGuarini** [comment]
goodnight and thanks!

**Pull request merged**
